plugin:  google.cloud.gcp_compute
projects:
    -  your-project-id
zones:
    -  europe-west3-a
    -  europe-west3-b
auth_kind:  application
scopes:
    -  https://www.googleapis.com/auth/cloud-platform
groups:
   gcp_linux:  "'linux'  in  labels.os_family"
    prod:  "labels.env  ==  'prod'"
    staging:  "labels.env  ==  'staging'"
    dev:  "labels.env ==  'dev'"
compose:
    ansible_host:  networkInterfaces[0].accessConfigs[0].natIP  |  default(networkInterfaces[0].networkIP)
