---
-  name:  GCP  post-patch  checks
    hosts:  gcp_linux
    gather_facts:  yes
    become:  yes

    roles:
       -  role:  gcp_linux_patching
            gcp_patching_phase:  "verify"
            tags: ["postcheck"]
